Animation call
ubcemergingmedialab/3DMetabolism pull request #24
Opened 2020-10-27 23:50 UTC by nkoda

# animation behavior functions

Status: ** Ready for review!**

Trello: **https://trello.com/c/TLCbRRnH**

## Changes
-  animation-behavior.component.js -> implemented animate() and stopAnimation() which are used to change the active variable in displace.shader.js 

## How to test-drive this PR
- I tested the functionality by appending animation-behavior on an edge and calling animate() and stopAnimation() with a GUI button.

## Research resources
- (link1)

## TODOS:

- [ ] Tests added
- [ ] Tests passed
- [ ] Build generated
- [ ] README.md updated

2020-10-28 22:23 UTC, hailin-zhang requested changes

2020-10-28 22:23 UTC, hailin-zhang commented on public/js/animation-behavior.component.js
> +            console.log('could not start animation of edge:' + this.el.getAttribute('id'));
should say `stop` instead of `start`

2020-10-28 23:00 UTC, nkoda commented on public/js/animation-behavior.component.js
> +            console.log('could not start animation of edge:' + this.el.getAttribute('id'));
good catch I'll fix that up

2020-10-29 07:22 UTC, hailin-zhang approved these changes

2020-10-29 21:57 UTC, merged